{:common=>
     {:cms_name=>"rubal"},
 :news=>
     {:news_on_page=>10,
      :installed=>false},
 :cache=>
     {:cache_by_dafault=>false,
      :auto_update=>true,
      :auto_update_time=>60*60*24},
}